# קונפיגורציית MkDocs לאתר התיעוד
site_name: בוט חילוץ בעלי חיים 🐕🚑
site_description: מערכת אוטומטית לדיווח ושיגור חילוץ בעלי חיים
site_author: צוות הפיתוח
site_url: https://amirbiron.github.io/Animals-rescue/

# ריפו
repo_name: animal-rescue-bot
repo_url: https://github.com/animal-rescue-bot/animal-rescue-bot
edit_uri: edit/main/docs/

# תמה וסגנון
theme:
  name: material
  language: he
  direction: rtl
  palette:
    # מצב בהיר
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: lime
      toggle:
        icon: material/brightness-7
        name: עבור למצב כהה
    # מצב כהה
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: lime
      toggle:
        icon: material/brightness-4
        name: עבור למצב בהיר
  
  font:
    text: Rubik
    code: Roboto Mono
  
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - toc.follow

# תוספים
plugins:
  - search:
      lang: 
        - he
        - en
        - ar
  - minify:
      minify_html: true

# תוספות Markdown
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html
  - tables
  - footnotes
  - toc:
      permalink: true
      toc_depth: 3

# ניווט
nav:
  - דף הבית: index.md
  - התחלה מהירה:
    - getting-started.md
    - quickstart.md
  - ארכיטקטורה:
    - architecture.md
    - api-reference.md
  - מדריכים:
    - admin-guide.md
  - פיתוח:
    - dev-guide.md
  - תפעול:
    - ops.md
  - נוסף:
    - faq.md

# נתונים נוספים
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/animal-rescue-bot
    - icon: fontawesome/brands/telegram
      link: https://t.me/AnimalRescueBot
  
  analytics:
    provider: google
    property: G-XXXXXXXXXX
  
  consent:
    title: הסכמה לעוגיות
    description: >- 
      אנחנו משתמשים בעוגיות כדי לזהות את ההעדפות שלך לביקורים חוזרים,
      למדוד את האפקטיביות של התיעוד שלנו ולהבין אם המשתמשים מוצאים
      את מה שהם מחפשים. בהסכמתך, אתה עוזר לנו לשפר את התיעוד.
    actions:
      - accept
      - reject

# זכויות יוצרים
copyright: >
  Copyright &copy; 2025 צוות בוט חילוץ בעלי חיים –
  <a href="#__consent">הגדרות עוגיות</a>