name: CI

on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgis/postgis:14-3.3
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        options: >-
          --health-cmd "pg_isready -U postgres -d test_db"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Init database schema
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db
          ENVIRONMENT: testing
          TESTING: '1'
          TELEGRAM_BOT_TOKEN: 'test-token'
          PYTHONPATH: ${{ github.workspace }}
        run: |
          python - <<'PY'
          import asyncio
          import os
          os.environ.setdefault('ENVIRONMENT','testing')
          os.environ.setdefault('TESTING','1')
          os.environ.setdefault('DATABASE_URL','postgresql+asyncpg://postgres:postgres@localhost:5432/test_db')
          from app.models.database import create_tables
          asyncio.run(create_tables())
          print('DB schema initialized')
          PY

      - name: Smoke import (no side effects)
        env:
          ENVIRONMENT: testing
          TESTING: '1'
          TELEGRAM_BOT_TOKEN: 'test-token'
          PYTHONPATH: ${{ github.workspace }}
        run: |
          python - <<'PY'
          import importlib
          import os
          os.environ.setdefault('ENVIRONMENT','testing')
          os.environ.setdefault('TESTING','1')
          os.environ.setdefault('TELEGRAM_BOT_TOKEN','test-token')
          os.environ.setdefault('DATABASE_URL','postgresql+asyncpg://postgres:postgres@localhost:5432/test_db')
          importlib.import_module('app.main')
          print('Imported app.main OK')
          PY

      - name: Run tests
        env:
          ENVIRONMENT: testing
          TESTING: '1'
          TELEGRAM_BOT_TOKEN: 'test-token'
          PYTHONPATH: ${{ github.workspace }}
        run: |
          export PYTHONPATH="$PWD"
          export DATABASE_URL="postgresql+asyncpg://postgres:postgres@localhost:5432/test_db"
          pytest -q

