name: Docs Preview

on:
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install MkDocs dependencies
        run: |
          if [ -f docs/requirements.txt ]; then
            pip install -r docs/requirements.txt
          else
            pip install mkdocs mkdocs-material mkdocs-minify-plugin
          fi

      - name: Build Docs
        run: mkdocs build --strict

      - uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/configure-pages@v5

      - id: deployment
        uses: actions/deploy-pages@v4
        with:
          preview: true

      - run: echo "Docs preview URL: ${{ steps.deployment.outputs.page_url }}" >> "$GITHUB_STEP_SUMMARY"

